package org.stenio.xframe.mapper.demo;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.stenio.xframe.model.demo.FileItem;
import org.stenio.xframe.model.demo.FileItemExample;

@Mapper
public interface FileItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    long countByExample(FileItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int deleteByExample(FileItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int insert(FileItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int insertSelective(FileItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    List<FileItem> selectByExample(FileItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    FileItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int updateByExampleSelective(@Param("record") FileItem record, @Param("example") FileItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int updateByExample(@Param("record") FileItem record, @Param("example") FileItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int updateByPrimaryKeySelective(FileItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_item
     *
     * @mbg.generated 2017-06-08 10;11:52
     */
    int updateByPrimaryKey(FileItem record);
}